[package]
name = "piesvg"
version = "0.1.0"
authors = ["noah"]
description = "produce pie chart svgs just like you always wanted to!"

[[bin]]
path = "src/main.rs"
name = "piesvg"

[dependencies]
clap = "2"
svg = "*"
